# Generated by Django 6.0.1 on 2026-03-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvpsubmission',
            name='guest_count',
        ),
        migrations.RemoveField(
            model_name='rsvpsubmission',
            name='meal',
        ),
        migrations.AddField(
            model_name='rsvpsubmission',
            name='alcohol',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rsvpsubmission',
            name='driving',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rsvpsubmission',
            name='food',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rsvpsubmission',
            name='music',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rsvpsubmission',
            name='soft_drinks',
            field=models.TextField(blank=True),
        ),
    ]
